name: CI
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      - name: Check format
        run: cargo fmt --check
      - name: Check
        run: RUSTFLAGS="-D warnings" cargo check
      # - name: Test
      #   run: cargo test
